version: '3'

services:
  # MySQL database for Magento
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - magento-db-data:/var/lib/mysql

  # Magento web server
  magento:
    image: alexcheng/magento2
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      MAGENTO_DB_HOST: db
      MAGENTO_DB_USER: magento
      MAGENTO_DB_PASSWORD: magento
      MAGENTO_DB_NAME: magento
      MAGENTO_ADMIN_USER: admin
      MAGENTO_ADMIN_PASSWORD: admin123
      MAGENTO_ADMIN_EMAIL: admin@example.com
      MAGENTO_BASE_URL: http://localhost:8080/
    volumes:
      - magento-data:/var/www/html

volumes:
  magento-db-data:
  magento-data:
  
